algo = input('Digite algo: ')
print ('que tipo primitivo é esse valor?', type(algo))
print ('só tem espaço?',algo.isspace())
print ('é alfanumérico?', algo.isalnum())
print ('é totalmente em letra minúscula?', algo.islower())
print ('é totalmente em letra maiúscula?', algo.isupper())
print ('está capitalizada?', algo.istitle())
print ('é somente letra?', algo.isalpha())
print ('é somente numérico?', algo.isnumeric())
print ('é {} que o valor {} é somente espaço.'.format(algo.isspace(), algo))
